package org.manathome.totask2.service;


/** analytical service interface. 
 * 
 * introduced to circumvent "no breakpoint can be set" in eclipse debugger with autogenerated spring interfaces.
 * */
public interface AnalyticService {
    
    /** generic, still missing: workEntry. */
    public void logData(final String category, final String key, final String data);
    
    /** changes on project, task... */
    public void logMasterDataChanges(final String entityName, final long entityId, final String instanceName); 
    
}

