package org.manathome.totask2.selenium;

import java.util.concurrent.TimeUnit;

import org.junit.*;

import static org.junit.Assert.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** 
 * selenium tests. 
 * 
 * test generated by selenium ide, modified by myself to avoid compile warnings.
 * 
 *  @author man-at-home
 **/
@Ignore("test needs an started totask2 web applications")
public class LoginProjectsLogout {

  private static final Logger LOG = LoggerFactory.getLogger(LoginProjectsLogout.class);
  
    
  private WebDriver driver;
  private String baseUrl;
  private StringBuffer verificationErrors = new StringBuffer();

  @Before
  public void setUp() throws Exception {
    driver = new FirefoxDriver();
    baseUrl = "http://localhost:8080/";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    
    LOG.debug("selenium: started firefox: " + driver.getCurrentUrl());
  }

  @Ignore("test needs an started totask2 web applications")
  @Test
  public void testLoginProjectsLogout() throws Exception {
      
    LOG.debug("selenium: running test..");
  
    // open | / | 
    driver.get(baseUrl + "/");
    // assertText | css=h1 | *totask2*
    assertTrue(driver.findElement(By.cssSelector("h1")).getText().matches("^[\\s\\S]*totask2[\\s\\S]*$"));
    // assertText | //a[contains(@href, '/weekEntry')] | edit weekly work hours..
    assertEquals("edit weekly work hours..", driver.findElement(By.xpath("//a[contains(@href, '/weekEntry')]")).getText());
    // click | link=projects.. | 
    driver.findElement(By.linkText("projects..")).click();
    // assertText | id=loginForm | *sign in*
    assertTrue(driver.findElement(By.id("loginForm")).getText().matches("^[\\s\\S]*sign in[\\s\\S]*$"));
    // type | name=username | unit-test-user
    driver.findElement(By.name("username")).clear();
    driver.findElement(By.name("username")).sendKeys("unit-test-user");
    // type | name=password | 123456
    driver.findElement(By.name("password")).clear();
    driver.findElement(By.name("password")).sendKeys("123456");
    // click | css=button.btn.btn-primary | 
    driver.findElement(By.cssSelector("button.btn.btn-primary")).click();
    // assertText | css=h1 | currently defined projects*
    assertTrue(driver.findElement(By.cssSelector("h1")).getText().matches("^currently defined projects[\\s\\S]*$"));
    // click | //button[@value='sign out'] | 
    driver.findElement(By.xpath("//button[@value='sign out']")).click();
    // assertText | css=div.container.paper-box | *you have been logged out*
    assertTrue(driver.findElement(By.cssSelector("div.container.paper-box")).getText().matches("^[\\s\\S]*you have been logged out[\\s\\S]*$"));
  }

  @After
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }


}
