-- feature enhancements:
--    project leads
--    task assignments
-- ---------------------------------------
-- @author man-at-home


-- project is leaded by

create table tt_project_project_leads 
(
	tt_project_ID bigint not null, 
	project_leads_id bigint not null, 
	primary key (tt_project_ID, project_leads_id)
);

alter table tt_project_project_leads 
      add constraint FK_TT_project_lead_by 
      foreign key (project_leads_id) 
      references tt_user
      ;

alter table tt_project_project_leads 
  add constraint FK_TT_project_leaded 
  foreign key (tt_project_ID) 
  references tt_project
  ;

-- task assignments  
  
create table tt_task_assignment 
(
	id bigint generated by default as identity, 
	starting_from date not null, 
	until date, task_id 
	bigint not null, 
	user_id bigint not null, 
	primary key (id)
);

alter table tt_task_assignment 
   add constraint FK_TT_ASSIGNMENT_TASK 
   foreign key (task_id) 
   references tt_task
   ;
   
alter table tt_task_assignment 
	add constraint FK_TT_ASSIGNMENT_USER 
	foreign key (user_id) 
	references tt_user
	;