-- history tables used by hibernate envers
-- ---------------------------------------
-- @author man-at-home

create table revinfo (rev integer generated by default as identity, revtstmp bigint, primary key (rev));

create table tt_project_history (id bigint not null, rev integer not null, revtype tinyint, name varchar(250), primary key (id, rev));
create table tt_project_project_leads_aud (rev integer not null, tt_project_id bigint not null, project_leads_id bigint not null, revtype tinyint, primary key (rev, tt_project_id, project_leads_id));
create table tt_task_assignment_history (id bigint not null, rev integer not null, revtype tinyint, starting_from date, until date, task_id bigint, user_id bigint, primary key (id, rev));
create table tt_task_history (id bigint not null, rev integer not null, revtype tinyint, name varchar(250), project_id bigint, primary key (id, rev));
create table tt_user_history (id bigint not null, rev integer not null, revtype tinyint, active boolean, display_name varchar(250), is_admin boolean, password varchar(100), user_name varchar(50), primary key (id, rev));

alter table tt_project_history add constraint FK_project_history 			foreign key (rev) references revinfo;
alter table tt_project_project_leads_aud add constraint FK_project_leads_history foreign key (rev) references revinfo;
alter table tt_task_assignment_history add constraint FK_assignment_history foreign key (rev) references revinfo;
alter table tt_task_history add constraint FK_task_history 					foreign key (rev) references revinfo;
alter table tt_user_history add constraint FK_user_history 					foreign key (rev) references revinfo;
